name: willow_mobile
description: "Willow BUT FOR MOBILEEEEE"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  window_manager: 0.3.7
  path: ^1.8.3
  provider: ^6.1.1
  filesize: ^2.0.1
  archive: ^4.0.7
  super_editor: 0.3.0-dev.23
  shared_preferences: ^2.5.4
  file_picker: ^8.1.8

  follow_the_leader: any
  overlord: any
  petitparser: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AppleColorEmoji
      fonts:
        - asset: assets/fonts/AppleColorEmoji.ttf


    - family: CrimsonPro
      fonts:
        - asset: assets/fonts/CrimsonPro-VariableFont_wght.ttf
        - asset: assets/fonts/CrimsonPro-Italic-VariableFont_wght.ttf
          style: italic

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/DMSans-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/IBMPlexSans-Italic-VariableFont_wdth,wght.ttf
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf
        - asset: assets/fonts/JetBrainsMono-Italic-VariableFont_wght.ttf
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
        - asset: assets/fonts/Lora-Italic-VariableFont_wght.ttf
          style: italic

    - family: MontaguSlab
      fonts:
        - asset: assets/fonts/MontaguSlab-VariableFont_opsz,wght.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf

    - family: ReCollectIcons
      fonts:
        - asset: assets/fonts/ReCollectIcons.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic

    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-VariableFont_wght.ttf
        - asset: assets/fonts/SourceCodePro-Italic-VariableFont_wght.ttf
          style: italic

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-VariableFont_wght.ttf
        - asset: assets/fonts/WorkSans-Italic-VariableFont_wght.ttf
          style: italic
